apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterserviceplans.servicecatalog.k8s.io
  labels:
    svcat: "true"
  annotations:
    api-approved.kubernetes.io: https://approve.me
spec:
  group: servicecatalog.k8s.io
  scope: Cluster
  names:
    plural: clusterserviceplans
    singular: clusterserviceplan
    kind: ClusterServicePlan
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
      - svcat
  versions:
    - name: v1beta1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: External-Name
          type: string
          jsonPath: .spec.externalName
        - name: Broker
          type: string
          jsonPath: .spec.clusterServiceBrokerName
        - name: Class
          type: string
          jsonPath: .spec.clusterServiceClassRef.name
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
