apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceinstances.servicecatalog.k8s.io
  labels:
    svcat: "true"
  annotations:
    api-approved.kubernetes.io: https://approve.me
spec:
  group: servicecatalog.k8s.io
  scope: Namespaced
  names:
    plural: serviceinstances
    singular: serviceinstance
    kind: ServiceInstance
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
      - svcat
  versions:
    - name: v1beta1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Class
          type: string
          jsonPath: .status.userSpecifiedClassName
        - name: Plan
          type: string
          jsonPath: .status.userSpecifiedPlanName
        - name: Status
          type: string
          jsonPath: .status.lastConditionState
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
